### ISSUE TITLE
Replace moment.js with Day.js

### ISSUE THREAD

**Issue by MacGyer** [tonix-tuft/tempusdominus-bootstrap#11]
Hey guys,

thanks for keeping the datepicker alive.

As moment.js has been discontinued as of lately (https://momentjs.com/docs/#/-project-status/): is there any chance to switch to Day.js (https://day.js.org/)?

**Comment by tonix-tuft** [comment]
Hello @MacGyer! Sounds intriguing, but I guess it would require a whole refactoring of both tempusdominus-bootstrap (this repo) as well as its core [tempusdominus](https://github.com/tonix-tuft/tempusdominus) and a new major version bump.

If you wanna start implementing this feature in new branch, you are welcome and I am willing to help and contribute as well, but I think it will require some time and effort because the overall codebase of this forked project is quite old and tightly coupled to Moment.

Let me know! Thank you!

**Comment by tonix-tuft** [comment]
BTW: Sorry for replying only now, but GitHub didn't send me a notification of this issue.

**Comment by MacGyer** [comment]
Hi @tonix-tuft,

thanks for getting back. Unfortunately, I am more a back end coder (PHP, SQL etc.) and not so much into front end dev (i. e. JS) :(

As I have seen there might be some interesting development in the original repo: https://eonasdan.com/posts/state-of-my-picker

**Comment by tonix-tuft** [comment]
I am closing this issue for now because Eonasdan (the original maintainer of tempusdominus-bootstrap) has come back and maybe this integration will happen in the upstream project. We'll see what happens.

Cheers!
